#!/usr/bin/env bash
# Regenerates daemon/THIRD-PARTY-NOTICES.md: the licence text of every Go module
# statically linked into the privileged helper.
#
# Unlike the executables under resources/linux/bin/, which are separate programs
# with their licence texts beside them, the helper LINKS these modules into one
# binary (tun2socks and its dependencies, since the engine was embedded), so their
# notices have to travel with the binary: the generated file ships next to
# THIRD-PARTY-LICENSES.md via electron-builder's extraResources. Apache-2.0 §4
# and the MIT/BSD attribution clauses are all satisfied by shipping the text.
#
# Run after any change to daemon/go.mod and commit the result; the module set is
# what `go list -deps` sees from the helper's main package, i.e. what the linker
# actually pulls in, not everything in go.sum.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/daemon/THIRD-PARTY-NOTICES.md"
cd "$ROOT/daemon"

mods="$(go list -deps -f '{{if and .Module (not .Standard)}}{{.Module.Path}}{{end}}' . | sort -u | grep -v '^katacomb.vpn/daemon$')"

{
  echo "# Third-party notices for the privileged helper"
  echo
  echo "\`katacomb-vpn-helper\` (built from \`daemon/\`, GPL-3.0-or-later like the rest of"
  echo "Katacomb VPN) statically links the Go modules below. Their licence texts follow,"
  echo "verbatim from each module at the pinned version. Generated by"
  echo "\`scripts/gen-go-notices.sh\` from \`go list -deps\`; regenerate after any change to"
  echo "\`daemon/go.mod\`."
  echo
  echo "| Module | Version |"
  echo "|---|---|"
  for m in $mods; do
    ver="$(go list -m -f '{{.Version}}' "$m")"
    echo "| \`$m\` | $ver |"
  done
  for m in $mods; do
    dir="$(go list -m -f '{{.Dir}}' "$m")"
    ver="$(go list -m -f '{{.Version}}' "$m")"
    lic="$(ls "$dir"/LICENSE* "$dir"/LICENCE* "$dir"/COPYING* 2>/dev/null | head -1 || true)"
    echo
    echo "## $m $ver"
    echo
    if [ -n "$lic" ]; then
      echo '```'
      cat "$lic"
      echo '```'
    else
      echo "(no licence file at the module root)"
    fi
  done
} > "$OUT"
echo "wrote $OUT ($(echo "$mods" | wc -l) modules)"
