#!/usr/bin/env bash
# Can the bundled `xray` binary replace the bundled `v2ray` one, so we ship one
# child-proxy core instead of two (~38 MB off the package)?
#
# Answer as of Xray 26.3.27 / V2Ray 5.47.0: NO. Two of the blockers cannot be
# fixed by rewriting the config, so this is not a "transform it and ship one
# binary" job. Re-run this after any xray bump; if it ever prints PARITY, the
# consolidation becomes possible and vpn-manager's resolveV2RayBinary() plus the
# binary-integrity pin are the only code that needs to change.
#
# The configs under test are the REAL ones: generated by the SDK's V2Ray class
# (which is what the v2ray connect path feeds the binary) for every
# transport x proxy-protocol x security combination it can emit, then run
# through the app's own transform chain from vpn-manager.connectV2Ray.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$ROOT/resources/linux/bin"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

for b in xray v2ray; do
  [ -x "$BIN/$b" ] || { echo "missing $BIN/$b" >&2; exit 1; }
done
NODE="${NODE:-node}"
command -v "$NODE" >/dev/null || { echo "node not on PATH (set NODE=)" >&2; exit 1; }

echo "xray:  $("$BIN/xray" version 2>/dev/null | head -1)"
echo "v2ray: $("$BIN/v2ray" version 2>/dev/null | head -1)"
echo

cat > "$WORK/gen.mjs" <<EOF
import { V2Ray } from '$ROOT/node_modules/@sentinel-official/sentinel-js-sdk/dist/vpn/v2ray/index.js'
import {
  withV2RayDiagnosticLog, pinV2RayNodeAddresses, assertSafeV2RayConfig, withV2RayDoH,
} from '$ROOT/src/main/config-guard.ts'
import { writeFileSync } from 'fs'

const TRANSPORT = { Unspecified:0, DomainSocket:1, GUN:2, GRPC:3, HTTP:4, MKCP:5, QUIC:6, TCP:7, WebSocket:8 }
const PROXY = { Unspecified:0, VLess:1, VMess:2 }
const SECURITY = { Unspecified:0, None:1, TLS:2 }

let n = 0
for (const [tn, t] of Object.entries(TRANSPORT))
  for (const [pn, p] of Object.entries(PROXY))
    for (const [sn, s] of Object.entries(SECURITY)) {
      const v = new V2Ray()
      await v.parseConfig({ metadata: [{ port:'8443', transport_protocol:t, proxy_protocol:p, transport_security:s }] }, ['203.0.113.10'])
      const cfg = pinV2RayNodeAddresses(withV2RayDiagnosticLog(v.config), (h) => h)
      assertSafeV2RayConfig(cfg)
      writeFileSync(\`$WORK/\${tn}_\${pn}_\${sn}.json\`, JSON.stringify(cfg, null, 2))
      writeFileSync(\`$WORK/\${tn}_\${pn}_\${sn}__doh.json\`, JSON.stringify(withV2RayDoH(cfg, '1.1.1.1'), null, 2))
      n += 2
    }
console.log(\`generated \${n} configs\`)
EOF
"$NODE" "$WORK/gen.mjs" 2>/dev/null | tail -1

pass_x=0; fail_x=0; pass_v=0; fail_v=0
declare -A reasons
for f in "$WORK"/*.json; do
  # Two passes for xray. As-is fails on the SDK's global `transport` block for
  # every config, which would mask everything behind it, so we also test with
  # that block stripped: it is all-empty defaults and IS a legitimate rewrite.
  # What still fails after that is what actually blocks the consolidation.
  "$NODE" -e "
    const {readFileSync,writeFileSync}=require('fs');
    const c=JSON.parse(readFileSync('$f','utf-8')); delete c.transport;
    writeFileSync('$WORK/stripped.json', JSON.stringify(c));"
  if "$BIN/xray" run -test -c "$WORK/stripped.json" >"$WORK/x.log" 2>&1; then pass_x=$((pass_x+1)); else
    fail_x=$((fail_x+1))
    # DomainSocket and GUN fail with no "The feature" line at all, so fall back
    # to the failure line, then to the log tail. Each grep must not trip set -e.
    r="$(grep -oE 'The feature [^.]*\.' "$WORK/x.log" | head -1 || true)"
    [ -n "$r" ] || r="$(grep -oE 'Failed to start.*' "$WORK/x.log" | head -1 | cut -c1-80 || true)"
    [ -n "$r" ] || r="(no diagnostic; transport not built into this xray)"
    reasons["$r"]=$(( ${reasons["$r"]:-0} + 1 ))
  fi
  if "$BIN/v2ray" test -c "$f" >/dev/null 2>&1; then pass_v=$((pass_v+1)); else fail_v=$((fail_v+1)); fi
done

echo
echo "v2ray accepts: $pass_v / $((pass_v+fail_v))"
echo "xray  accepts: $pass_x / $((pass_x+fail_x))   (after stripping the global transport block)"
echo
if [ "$fail_x" -gt 0 ]; then
  echo "xray rejection reasons:"
  for r in "${!reasons[@]}"; do printf '  %4d  %s\n' "${reasons[$r]}" "$r"; done | sort -rn
  echo
  echo "RESULT: NO PARITY. Keep shipping both binaries."
  echo "  Blockers with no config-level workaround:"
  echo "    - allowInsecure removed (nodes use self-signed certs; we have no"
  echo "      cert pin for plain V2Ray nodes to migrate to pinnedPeerCertSha256)"
  echo "    - http / quic / domainsocket / gun transports removed"
  echo "  Blockers that COULD be rewritten, listed so nobody re-derives them:"
  echo "    - the SDK's global 'transport' block (all-empty defaults; xray wants"
  echo "      per-outbound streamSettings)"
  echo "    - routing.balancers strategy 'leastping' needs an observatory in xray"
  exit 1
fi
echo "RESULT: PARITY. xray accepts every config v2ray does."
echo "  The v2ray binary can be dropped: point resolveV2RayBinary() at 'xray',"
echo "  remove the v2ray pin from binary-integrity.ts and delete the binary."
